### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by b34c0n5**
Added CLI one-liner for Ubuntu/Debian dependencies

### CODE REVIEW

**Review by eversiege — APPROVED** [review]
LGTM!

**Comment by Coopydood** [comment]
Could possibly style it as a dropdown along with other OSes?

Example:

<details><summary><h4>Arch</h4></summary>

```sh
a
```
</details>

<details><summary><h4>Ubuntu / Debian</h4></summary>

```sh
sudo apt-get install qemu uml-utilities virt-manager git \
    wget libguestfs-tools p7zip-full make dmg2img tesseract-ocr \
    tesseract-ocr-eng genisoimage vim net-tools screen -y
```
</details>

**Comment by Coopydood** [comment]
And if you can, please ensure you're up to date with the ``dev`` branch, and pull request to that instead.

Many thanks

**Comment by b34c0n5** [comment]
Sure, will do.

**Pull request closed without merging**
