### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by b34c0n5**
Added Arch/Debian-based one-liners to install dependencies.

### CODE REVIEW

**Comment by b34c0n5** [comment]
@Coopydood - as you suggested.

**Comment by eversiege** [comment]
I have never seen a Pull Request as broken as this one.

**Comment by eversiege** [comment]
Pushed a commit to organise commands in code blocks, instead of lines

**Comment by b34c0n5** [comment]
added yay variant for virsh as a tip

**Pull request closed without merging**
